### ISSUE TITLE
Alexa Playlist Issue

### ISSUE THREAD

**Issue by MrSteave** [ndg63276/alexa-youtube#133]
More often than not, Alexa will not play a playlist and will instead play a video that sounds similar, but when I ask her "Play my playlist 'playlist name'" she will respond with "I wasn't able to play a video" no matter which playlist I choose. (All of them are public and my channel ID is in the ARN) She has played videos from other playlists though, and she can play "My latest video", so I'm not sure what the issue is?

**Comment by ndg63276** [comment]
YouTube is bad at searching playlists. I guess it takes a long time for them all to be indexed, or something, because search results are terrible for playlists.

You can see the search results for a query by going to:

https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&type=playlist&q={PLAYLIST_NAME}&key={DEVELOPER_KEY}

Or just searching on youtube.com with the filter 'playlists' on.
