### ISSUE TITLE
Repetition in Playlist

### ISSUE THREAD

**Issue by coot66** [ndg63276/alexa-youtube#26]
I have a playlist with over 100 songs. It seems like it just shuffles through 10 or so. Can you make it randomly select from the full playlist or (better yet) keeps track of what songs it played already?

**Comment by ndg63276** [comment]
Hi, can you send me a link to the playlist?

**Comment by coot66** [comment]
> Hi, can you send me a link to the playlist?

https://www.youtube.com/playlist?list=PLQbB7kzsz09jvgnZHxGpiVOv6RVaFYBhC

**Comment by ndg63276** [comment]
Thanks.

I found a couple of bugs in my code, it was only selecting the first 25 videos in the playlist, and then shuffling them, so you would have had lots of repeats. It now gets up to 200 videos, shuffles, and then plays the first 50 randomly. Limited to 50 because I store the videos in the audioplayer token, which has a max length of 1024 characters.

It still doesn't keep track of what it has played, I will look at that later.

**Comment by ndg63276** [comment]
OK, now, if you shuffle a playlist or channel, videos are removed from the Alexa playlist once they end, or are skipped. Let me know if it works for you.

**Comment by coot66** [comment]
> OK, now, if you shuffle a playlist or channel, videos are removed from the Alexa playlist once they end, or are skipped. Let me know if it works for you.

Seems to be working better. Thanks! Is it still limited to 50 songs at this point?

**Comment by ndg63276** [comment]
Yes, 50 songs is about the limit with how I store the playlist.
